version: '3'
volumes:
  sonar-conf:
  sonar-extensions:
  sonar-data:
networks:
  internal:
    driver: bridge
services:
  es-container:
    depends_on:
      - sonarqube
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash -c 'while sleep 1000;do true;done'
    #--device /dev/fuse --cap-add SYS_ADMIN --security-opt apparmor:unconfined
    devices:
      - /dev/dri
      - /dev/fuse
      - /dev/snd
    cap_add:
      - SYS_ADMIN
    security_opt:
      - 'apparmor:unconfined'
    networks:
      - internal
    volumes:
#      - $HOME/.local/share/endless-sky:/home/es-user/.local/share/endless-sky
      - ../../../endless-sky:/workspace/endless-sky
      - ../.vscode:/workspace/endless-sky/.vscode
      - .:/workspace/endless-sky/.devcontainer
      - ./clang-format:/workspace/endless-sky/.clang-format
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/${UID:-1000}/pulse/native:/run/user/${UID:-1000}/pulse/native
    environment:
      DISPLAY: $DISPLAY
      PULSE_SERVER: unix:/run/user/${UID:-1000}/pulse/native
  sonarqube:
    init: true
    # https://hub.docker.com/_/sonarqube/
    image: sonarqube
    networks:
      - internal
    volumes:
      - sonar-conf:/opt/sonarqube/conf
      - sonar-extensions:/opt/sonarqube/extensions
      - sonar-data:/opt/sonarqube/data
    ports:
      - localhost:9000:9000
